default:
  iface1:
    name: "wlan1"
    host: 192.168.93.13
    gateway: 192.168.93.1
  iface2:
    name: "wlan0"
    host: 192.168.34.128
    gateway: 192.168.34.1
  server:
    name: "quic.smalldragon.net"
    host: 155.230.34.241
  single:
    ssid1: "SD-WiFi"
    pass1: "thdyd324!"
    ssid2: "SD-WiFi-ATC-5G"
    pass2: "thdyd324"